# == Zuul configuration file ==
#
# This file is used to configure this project and its associated jobs in Zuul.
# Zuul is the CI/CD tool which lets us check changes before they are committed,
# and build a canary version of the extension on a regular basis.
#
# More info about Zuul: https://zuul-ci.org/docs/zuul/

- job:
    name: infinitegforums-lint
    parent: web-ext-lint
    pre-run: playbooks/lint/pre.yaml
    run: playbooks/lint/run.yaml
    post-run: playbooks/lint/post.yaml
    vars:
      use_standalone_web_ext: false
      web_ext_command: "./node_modules/web-ext/bin/web-ext.js"
    irrelevant-files:
      - ".github/.*"
      - "docs/.*"
      - ".*/?OWNERS"
      - ".gitreview"
      - "README.md"
      - "renovate.json"
      - "cws/.*"
      - "roles/cws-publish/*"
      - "roles/fetch-cws-log/*"
      - "playbooks/nightly-build/*"

- job:
    name: infinitegforums-test-nightly-build
    pre-run: playbooks/nightly-build/pre.yaml
    run: playbooks/nightly-build/test.yaml
    roles:
      - zuul: zuul/jobs
    vars:
      credentials:
        clientId: "testClientId"
        refreshToken: "testRefreshToken"
    files:
      - "roles/cws-publish/*"
      - "playbooks/nightly-build/*"

- job:
    name: infinitegforums-nightly-build
    attempts: 1
    pre-run: playbooks/nightly-build/pre.yaml
    run: playbooks/nightly-build/run.yaml
    post-run: playbooks/nightly-build/post.yaml
    roles:
      - zuul: zuul/jobs
    secrets:
      - name: credentials
        secret: credentials_twpt

- project:
    check:
      jobs:
        - infinitegforums-test-nightly-build
        - infinitegforums-lint
    nightly-build:
      jobs:
        - infinitegforums-nightly-build

# Secrets generated via https://github.com/fregante/chrome-webstore-upload-keys
- secret:
    name: credentials_twpt
    data:
      clientId: !encrypted/pkcs1-oaep
        - PB2yhixAGYf3rNYfSuetIwbbrd/o5xq813LJHQThIwfxkvwmZstx6r/SsIcAKqo1qWKW/
          j2KTTWUp4JaNvc+x8s8M2uu+auo65A9/YMDTx6FAfjOlVnYhvztOBz5hKqkrxy18nFzdo
          uZ6KWZGKioU2oVjx18DAx8ocldo3Ur3bWXMSG1rF8xAa2AhHw7cedrQGrleL3ODGj0zah
          45eGiCRZnup5vMn0F+eKaTVuwkrOtdVJC9zFd7biNP33V6vAa3SSNnG8Fo4ylbYmOh0XN
          2R6hI4UaE92McHULLvJUYBdhUhCYcg29cfkMGzAD/63r2SlqLVRY9T+jbs+U5WOF0Qpqg
          /t+v0lwgjQzmgZDfy54JiirmZUpiQBahQwI2yoT2CW8vMhPV2T57Ie0f3stGTj3VUjQrQ
          MKD9+ofsWh8s6axJHcYLFtjLxFueW7aqPK0SxU32O/22OLWgpup2fU3hiHv0eY/h8p9ie
          tnwG/O81Nh34iRAP+aINQVU3jvI51TVOxJ7c0J0VuGDiyy1I8N3pS20pG8LNBFODtXfky
          SCk7EDTaPfotcyGmDwfkMQJ2OvO4Na4x7af3EresL4AQAKE0l0JUdeC8yv+4KbxxYvarN
          kSiGvNsk7Mgn2E66UQ68RKgKUqbkKHLnlEhLcxYZ2vfhUOuSs8P3c9wqw4msyk=
      clientSecret: !encrypted/pkcs1-oaep
        - m3N6EPjJVoQY7spZTSdSxe4l66nmEeHM4xbE5desTaoFEkdngDQHQ6gdDksLCpoP6eTse
          3/9HQstdSBYPrPBw3be89FVx3MtbhcJtLVLYKnLqP+BRajN9KbdSF1qJFjsGnkKFoKPNl
          52k4iWVXaaq24ZKLlP/0pMqR0VryEACCb9Ms//mcPVFx5nVWsI4rVHZ8UDEgN+J2nHapR
          k1WQaUd1sPBMD9CICFbh6A6yOYL2huCgFQmiCDFxcJ8/4A0ZsEqqnEjGEBdKJ/t8SfFF0
          e0FRlfvakenvX8trHoOYySWAkjbIT0NaAjExJrg2ot0dlOxFzJAGKNsi3BhNjBSDYZtzV
          YOEaBcnfDFCx86j54KtbG9v7+KdJR2HMyqNqnoID9YnuBRucwkVlX4jIx6uPwKjaWuR7c
          H4a2FL+5tQMd3cPhsqtQKs/4wNwG84rCNCfdOVcrXNbjtZLlNYUO8+wdYlmzimCiXoo0/
          Oxl1JWyAbwo04CdvsS4mINOQIDqn1Y0CL7h67OxbPD7LuJlanZddpMza9poRZXxR10P6x
          4Ok2QL3VyiBkFlu+roDogCU5pbrD2a/pmr8g0L1cdLxdf4OAL2mS/SxBLIKhXX53OfZBv
          7Eag/isbaz7FOWkybg1H45VUCzc5Da1U31TR8KP15aAmrWNK+HRpgxfgwPBSq4=
      refreshToken: !encrypted/pkcs1-oaep
        - st4DQML37qesOPUz6JR7CxG12vy+1JDFPzdFqZe4AknazRICpnJN78MgE3XgONRd1GJIC
          /pphxqFOeJwEMSWsyN7a/FHAOnilKOHb4EKgvviXWGc1kMe0T4nammMSObhMmiy7DNFDd
          Tdj60BphFAISyB24bu1rb3oc+Mi5lOxTb4GkXTGUs8+w+Z/PI/QOxfhVkPq2wvKKsfbwx
          xXbtjzveHO4hswKX2ER0lk6wBSdgBcwQuKikHB2kBr242sCTnOJ7pZ6/xscwepEbFAQm0
          oH74K3LLB3eyYfeJlTO6W413AQcrSDtdzltbLrbgol1AsOVrv1q66c5Qr3smU9D5Ek8NO
          LSTUjty6CPxG9/ifnWyZVCgtyuswDAmGToEA6vepUknQZz2Lfe2yAhkwj3mVQp9pFy2mX
          JIXqdkdbKf3Tvee8x+ISaMTSuvNxpgGy18uBW4mBE1s79q8OylgK1NaYLyVfzXJ9vmYtf
          U8x/vbRiCH846hCWQWBw1PjkGzT++VBs/upxSBMkopCgwiTsX0uge+U2lHhXL7D11BWlP
          fuk/oyTfWHL8uXdURjY3Av0OpqpxBt0436yfHW3Jv++XhYQMKtjAr8iPuWeKLglJoZQby
          89Q/4511iJzrIBNzjHGicmVIuJZQGwIkp38YjnEtpMZlwp85Pg10fN54YeTibE=
