const kItemMetadataStateEnum = {
  UNDEFINED: 0,
  PUBLISHED: 1,
  DRAFT: 2,
  AUTOMATED_ABUSE_TAKE_DOWN_HIDE: 3,
  AUTOMATED_ABUSE_TAKE_DOWN_DELETE: 4,
  AUTOMATED_ABUSE_REINSTATE: 13,
  AUTOMATED_OFF_TOPIC_HIDE: 10,
  AUTOMATED_FLAGGED_PENDING_MANUAL_REVIEW: 14,
  USER_FLAGGED_PENDING_MANUAL_REVIEW: 5,
  OWNER_DELETED: 6,
  MANUAL_TAKE_DOWN_HIDE: 7,
  MANUAL_PROFILE_TAKE_DOWN_SUSPEND: 17,
  MANUAL_TAKE_DOWN_DELETE: 8,
  REINSTATE_PROFILE_TAKEDOWN: 18,
  REINSTATE_ABUSE_TAKEDOWN: 9,
  CLEAR_OFF_TOPIC: 11,
  CONFIRM_OFF_TOPIC: 12,
  GOOGLER_OFF_TOPIC_HIDE: 15,
  EXPERT_FLAGGED_PENDING_MANUAL_REVIEW: 16,
  AWAITING_CLASSIFICATION: 19,
};

export default kItemMetadataStateEnum;
