export const kUserRoleEnum = {
  ROLE_USER: 0,
  ROLE_PRODUCT_EXPERT_LEVEL_1: 1,
  ROLE_PRODUCT_EXPERT_LEVEL_2: 2,
  ROLE_PRODUCT_EXPERT_LEVEL_3: 3,
  ROLE_PRODUCT_EXPERT_LEVEL_4: 4,
  ROLE_PRODUCT_EXPERT_LEVEL_5: 5,
  ROLE_COMMUNITY_MANAGER: 10,
  ROLE_COMMUNITY_SPECIALIST: 20,
  ROLE_GOOGLE_EMPLOYEE: 100,
  ROLE_ALUMNUS: 30,
};
export default kUserRoleEnum;

export const kUserRoleRank = {
  [kUserRoleEnum.ROLE_USER]: 0,
  [kUserRoleEnum.ROLE_ALUMNUS]: 1,
  [kUserRoleEnum.ROLE_PRODUCT_EXPERT_LEVEL_1]: 2,
  [kUserRoleEnum.ROLE_PRODUCT_EXPERT_LEVEL_2]: 3,
  [kUserRoleEnum.ROLE_PRODUCT_EXPERT_LEVEL_3]: 4,
  [kUserRoleEnum.ROLE_PRODUCT_EXPERT_LEVEL_4]: 5,
  [kUserRoleEnum.ROLE_PRODUCT_EXPERT_LEVEL_5]: 6,
  [kUserRoleEnum.ROLE_COMMUNITY_SPECIALIST]: 7,
  [kUserRoleEnum.ROLE_COMMUNITY_MANAGER]: 8,
  [kUserRoleEnum.ROLE_GOOGLE_EMPLOYEE]: 9,
};
